
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frqansjbzjdfxvilfcig.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZycWFuc2piempkZnh2aWxmY2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTI5MTIsImV4cCI6MjA2Mzk2ODkxMn0.hUvPgFTw7J-niZOiidHbFnZ_zuudTtxudoVfHnY85Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
